apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp-deploy
  labels:
    app: java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp
          # Use your account/region repo; CI will update this to the build tag
          image: 085089485008.dkr.ecr.us-east-2.amazonaws.com/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---

# LoadBalancer Service for java-webapp
apiVersion: v1
kind: Service
metadata:
  name: java-webapp-svc
  labels:
    app: java-webapp
spec:
  selector:
    app: java-webapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
